from __future__ import annotations


def _adapter(
    *,
    mode: str,
    lifecycle: str,
    reference: str,
    boundary: str,
    input_contract: str,
    output_contract: str,
    fallback: str,
    exit_strategy: str,
) -> dict[str, str]:
    return {
        "mode": mode,
        "lifecycle": lifecycle,
        "reference": reference,
        "boundary": boundary,
        "input_contract": input_contract,
        "output_contract": output_contract,
        "fallback": fallback,
        "exit_strategy": exit_strategy,
    }


def standard_adapter_registry() -> dict[str, dict[str, str]]:
    return {
        "slsa": _adapter(
            mode="native-standard",
            lifecycle="adapter",
            reference="https://slsa.dev/spec",
            boundary="Evidence and release facts may project to SLSA-style provenance.",
            input_contract="ETHOS EvidenceSet plus release subject digest.",
            output_contract="SLSA provenance predicate projection.",
            fallback="Keep unsigned JSON evidence with HEAD and digest binding.",
            exit_strategy="Remove the projection while preserving ETHOS Evidence schema.",
        ),
        "in_toto": _adapter(
            mode="attestation-envelope",
            lifecycle="adapter",
            reference="https://in-toto.io/",
            boundary="Wrap ETHOS evidence sets as statement envelopes.",
            input_contract="ETHOS provenance envelope.",
            output_contract="in-toto statement-shaped attestation.",
            fallback="Emit ETHOS provenance JSON without external envelope publication.",
            exit_strategy="Drop envelope projection while keeping evidence digest binding.",
        ),
        "sigstore": _adapter(
            mode="first-class-adapter",
            lifecycle="optional",
            reference="https://www.sigstore.dev/",
            boundary="Sign artifacts or evidence projections; do not own truth.",
            input_contract="Release artifact digest or evidence digest.",
            output_contract="Signature and transparency-log reference.",
            fallback="Use local digest verification and Git-signed release tags.",
            exit_strategy="Disable signing adapter without changing proof semantics.",
        ),
        "spdx": _adapter(
            mode="artifact-metadata-adapter",
            lifecycle="adapter",
            reference="https://spdx.dev/",
            boundary="Project release package metadata and SBOM facts.",
            input_contract="Workspace package metadata and lock data.",
            output_contract="SPDX-compatible SBOM projection.",
            fallback="Keep package metadata and dependency lock evidence.",
            exit_strategy="Remove SBOM projection without changing release readiness.",
        ),
        "cdevents": _adapter(
            mode="event-interchange-adapter",
            lifecycle="optional",
            reference="https://cdevents.dev/",
            boundary="Project Chronicle and gate events to CI/CD event streams.",
            input_contract="ETHOS Chronicle event.",
            output_contract="CDEvents-compatible event projection.",
            fallback="Keep SQLite events and JSONL exports.",
            exit_strategy="Disable event export while preserving Chronicle semantics.",
        ),
        "opentelemetry": _adapter(
            mode="native-standard",
            lifecycle="optional",
            reference="https://opentelemetry.io/docs/specs/semconv/",
            boundary="Use semantic conventions for Chronicle and action run telemetry.",
            input_contract="Action run and gate timing event.",
            output_contract="OpenTelemetry semantic event projection.",
            fallback="Emit structured JSON events without telemetry export.",
            exit_strategy="Drop exporter while retaining Chronicle events.",
        ),
        "dagger": _adapter(
            mode="runner-adapter",
            lifecycle="experimental",
            reference="https://dagger.io/",
            boundary="Run action graph nodes in programmable local or hosted CI containers.",
            input_contract="ETHOS ActionGraph node.",
            output_contract="ActionRunResult compatible run record.",
            fallback="Use local subprocess runner over the same action graph.",
            exit_strategy="Remove runner adapter without changing action graph schema.",
        ),
        "cue": _adapter(
            mode="advanced-compiler",
            lifecycle="experimental",
            reference="https://cuelang.org/",
            boundary="Compile advanced organization profiles into .ethos TOML and schemas.",
            input_contract="Organization policy source.",
            output_contract="Generated TOML and JSON Schema projections.",
            fallback="Use TOML plus JSON Schema validation.",
            exit_strategy="Keep generated TOML and retire the compiler projection.",
        ),
        "opa": _adapter(
            mode="policy-adapter",
            lifecycle="optional",
            reference="https://www.openpolicyagent.org/",
            boundary="Evaluate organization policy over ETHOS JSON payloads.",
            input_contract="ETHOS result, action, evidence, or project JSON.",
            output_contract="Policy decision record.",
            fallback="Use Python policy checks inside ethos-repository.",
            exit_strategy="Remove policy adapter while keeping policy decision contract.",
        ),
        "temporal": _adapter(
            mode="service-runtime-adapter",
            lifecycle="experimental",
            reference="https://temporal.io/",
            boundary="Durable service-mode execution for long campaigns and agent swarms.",
            input_contract="Campaign action graph and state transition events.",
            output_contract="Chronicle-compatible workflow event export.",
            fallback="Use local CLI and SQLite state.",
            exit_strategy="Export Chronicle events and stop service-mode workflows.",
        ),
        "mcp": _adapter(
            mode="agent-projection",
            lifecycle="native",
            reference="https://modelcontextprotocol.io/",
            boundary="Expose ETHOS resources, prompts, and tools to agent hosts.",
            input_contract="ETHOS command JSON, docs, and schemas.",
            output_contract="MCP resource and tool manifest.",
            fallback="Use CLI JSON and docs context packs.",
            exit_strategy="Remove host projection without changing repository truth.",
        ),
    }
