"""Read the exact repository-family Git hook runtime binding."""

from __future__ import annotations

import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import uuid
from contextlib import contextmanager
from importlib.metadata import PackageNotFoundError
from importlib.metadata import distribution
from pathlib import Path
from typing import TYPE_CHECKING
from typing import TypedDict

if TYPE_CHECKING:
    from collections.abc import Iterator

HOOK_NAMES = ("pre-commit", "pre-push", "reference-transaction")
_GIT = shutil.which("git") or "git"
_RUNTIME_LOCATOR = (
    r"\.\./ethos/runtime/(?P<digest>[a-f0-9]{64})/venv/(?P<python>bin/python|Scripts/python\.exe)"
)
_RUNTIME_RELATIVE = re.compile(f"^{_RUNTIME_LOCATOR}$")
_RUNTIME_IN_LAUNCHER = re.compile(_RUNTIME_LOCATOR)


def _git_common_dir(root: Path) -> Path:
    common = Path(_git(root, "rev-parse", "--git-common-dir").stdout.strip())
    return common.resolve() if common.is_absolute() else (root / common).resolve()


class HookRuntimeBinding(TypedDict):
    """One repository family's exact generated-hook runtime provenance."""

    hooks_path: str
    runtime_manifest_path: str
    runtime_digest: str
    wheel_sha256: str
    python: str
    scripts: list[str]
    required_gaps: list[str]


def hook_launcher(runtime: str, name: str) -> str:
    """Render a Git-shell projection over one validated relative runtime."""
    if name not in HOOK_NAMES:
        message = f"hook_name_invalid:{name}"
        raise ValueError(message)
    if _RUNTIME_RELATIVE.fullmatch(runtime) is None:
        message = "hook_runtime_locator_invalid"
        raise ValueError(message)
    return (
        "#!/bin/sh\n"
        "# Generated by ethos hook install; Python owns all hook semantics.\n"
        'HOOK_DIR=${0%/*}; [ "$HOOK_DIR" = "$0" ] && HOOK_DIR=.\n'
        'HOOK_DIR=$(CDPATH= cd "$HOOK_DIR" && pwd)\n'
        f'exec "$HOOK_DIR/{runtime}" -I -m ethos.cli hook run {name} "$@"\n'
    )


def hook_runtime_binding(root: Path) -> HookRuntimeBinding:
    """Observe the configured common-dir runtime and its generated launchers."""
    repo = root.resolve()
    common = _git_common_dir(repo)
    hooks = common / "ethos-hooks"
    configured = _configured_hooks_path(repo)
    runtime, manifest, digest, wheel = _runtime_from_launcher(hooks / "pre-commit")
    gaps: list[str] = []
    if configured != hooks:
        gaps.append("write_admission_not_armed:core.hooksPath")
    if runtime is None or manifest is None:
        gaps.append("write_admission_not_armed:runtime_manifest")
    if runtime is None:
        gaps.append("write_admission_not_armed:runtime_python")
    for name in HOOK_NAMES:
        launcher = hooks / name
        if not launcher.is_file() or not os.access(launcher, os.X_OK):
            gaps.append(f"write_admission_not_armed:{name}_launcher_missing")
        elif runtime is not None and launcher.read_text(encoding="utf-8") != hook_launcher(
            _runtime_locator(digest, runtime), name
        ):
            gaps.append(f"write_admission_not_armed:{name}_launcher_drift")
    return {
        "hooks_path": hooks.as_posix(),
        "runtime_manifest_path": manifest.as_posix() if manifest else "",
        "runtime_digest": digest,
        "wheel_sha256": wheel,
        "python": runtime.as_posix() if runtime else "",
        "scripts": list(HOOK_NAMES),
        "required_gaps": gaps,
    }


def hook_runtime_transaction_environment(root: Path) -> dict[str, str]:
    """Bind one Git transaction to the already validated package hook runtime."""
    binding = hook_runtime_binding(root)
    runtime_gaps = [
        gap for gap in binding["required_gaps"] if gap != "write_admission_not_armed:core.hooksPath"
    ]
    if runtime_gaps:
        message = runtime_gaps[0]
        raise ValueError(message)
    return {
        "GIT_CONFIG_COUNT": "1",
        "GIT_CONFIG_KEY_0": "core.hooksPath",
        "GIT_CONFIG_VALUE_0": binding["hooks_path"],
    }


@contextmanager
def initiating_hook_transaction(root: Path) -> Iterator[dict[str, str]]:
    """Create one exact current-process hook projection for a bounded Git transaction."""
    executable = Path(sys.executable)
    try:
        package = distribution("ethos")
    except PackageNotFoundError as error:
        message = "hook_transaction_distribution_missing"
        raise ValueError(message) from error
    prefix = Path(sys.prefix).resolve()
    location = Path(str(package.locate_file(""))).resolve()
    if (
        not executable.is_absolute()
        or not executable.is_file()
        or not location.is_relative_to(prefix)
        or not package.version
    ):
        message = "hook_transaction_runtime_invalid"
        raise ValueError(message)
    hooks = _git_common_dir(root) / "ethos" / "transactions" / uuid.uuid4().hex / "hooks"
    hooks.mkdir(parents=True)
    try:
        executable_name = executable.relative_to(prefix).as_posix()
    except ValueError:
        executable_name = executable.name
    manifest = hooks.parent / "manifest.json"
    manifest.write_text(
        json.dumps(
            {
                "schema_version": 1,
                "distribution": "ethos",
                "version": package.version,
                "python_executable": executable_name,
                "python_prefix": prefix.as_posix(),
                "runtime_files": {executable_name: _sha256(executable)},
            },
            sort_keys=True,
            separators=(",", ":"),
        )
        + "\n",
        encoding="utf-8",
    )
    launcher = (
        "#!/bin/sh\n"
        "# Generated for one ETHOS Git transaction.\n"
        f'ETHOS_HOOK_TRANSACTION_ROOT="{root.resolve().as_posix()}"; '
        "export ETHOS_HOOK_TRANSACTION_ROOT\n"
        f'exec "{executable.as_posix()}" -I -m ethos.cli hook run "$0" "$@"\n'
    )
    try:
        for name in HOOK_NAMES:
            target = hooks / name
            target.write_text(launcher.replace('"$0"', name), encoding="utf-8", newline="\n")
            target.chmod(0o755)
        yield {
            "GIT_CONFIG_COUNT": "1",
            "GIT_CONFIG_KEY_0": "core.hooksPath",
            "GIT_CONFIG_VALUE_0": hooks.as_posix(),
        }
    finally:
        shutil.rmtree(hooks.parent, ignore_errors=True)


def _runtime_from_launcher(launcher: Path) -> tuple[Path | None, Path | None, str, str]:
    if not launcher.is_file():
        return None, None, "", ""
    match = _RUNTIME_IN_LAUNCHER.search(launcher.read_text(encoding="utf-8"))
    if match is None:
        return None, None, "", ""
    digest = match["digest"]
    runtime = launcher.parent.parent / "ethos" / "runtime" / digest / "venv" / match["python"]
    manifest = runtime.parents[2] / "manifest.json"
    try:
        payload = json.loads(manifest.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None, manifest, "", ""
    wheel = str(payload.get("wheel_sha256") or "")
    files = payload.get("runtime_files")
    relative_runtime = runtime.relative_to(manifest.parent).as_posix()
    valid = (
        payload.get("schema_version") == 1
        and payload.get("runtime_digest") == digest
        and len(wheel) == 64
        and not (set(wheel) - set("0123456789abcdef"))
        and isinstance(payload.get("python_abi"), str)
        and bool(payload["python_abi"])
        and isinstance(payload.get("platform"), str)
        and bool(payload["platform"])
        and isinstance(files, dict)
        and runtime.is_file()
        and files.get(relative_runtime) == _sha256(runtime)
    )
    return (runtime, manifest, digest, wheel) if valid else (None, manifest, "", "")


def _runtime_locator(digest: str, runtime: Path) -> str:
    executable = "Scripts/python.exe" if runtime.parent.name == "Scripts" else "bin/python"
    return f"../ethos/runtime/{digest}/venv/{executable}"


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _configured_hooks_path(root: Path) -> Path | None:
    completed = _git(root, "config", "--path", "--get", "core.hooksPath", check=False)
    if completed.returncode or not completed.stdout.strip():
        return None
    configured = Path(completed.stdout.strip())
    return configured if configured.is_absolute() else (root / configured).resolve()


def _git(root: Path, *args: str, check: bool = True) -> subprocess.CompletedProcess[str]:
    environment = {key: value for key, value in os.environ.items() if not key.startswith("GIT_")}
    environment.update(
        {
            "GIT_NO_REPLACE_OBJECTS": "1",
            "GIT_OPTIONAL_LOCKS": "0",
            "GIT_CONFIG_NOSYSTEM": "1",
            "GIT_CONFIG_GLOBAL": os.devnull,
            "GIT_ATTR_NOSYSTEM": "1",
        }
    )
    return subprocess.run(
        (_GIT, *args),
        cwd=root,
        capture_output=True,
        check=check,
        text=True,
        env=environment,
    )
