"""Read the exact worktree-local Git hook runtime binding."""

from __future__ import annotations

import os
import shlex
import shutil
import subprocess
from pathlib import Path
from typing import TypedDict

HOOK_NAMES = ("pre-commit", "pre-push", "reference-transaction")
_GIT = shutil.which("git") or "git"


class HookRuntimeBinding(TypedDict):
    """One checkout's exact generated-hook runtime provenance."""

    hooks_path: str
    runtime_metadata_path: str
    python: str
    scripts: list[str]
    required_gaps: list[str]


def hook_launcher(python: str, name: str) -> str:
    """Render one Git-required shell projection over the Python hook owner."""
    if name not in HOOK_NAMES:
        message = f"hook_name_invalid:{name}"
        raise ValueError(message)
    return (
        "#!/bin/sh\n"
        "# Generated by ethos hook install; Python owns all hook semantics.\n"
        f'exec {shlex.quote(python)} -I -m ethos.cli hook run {name} "$@"\n'
    )


def hook_runtime_binding(root: Path) -> HookRuntimeBinding:
    """Observe one checkout's configured hook path and exact Python provenance."""
    repo = root.resolve()
    hooks = _git_path(repo, "ethos-hooks")
    metadata = _git_path(repo, "ethos-runtime-python")
    configured = _configured_hooks_path(repo)
    python = _runtime_python(metadata)
    gaps: list[str] = []
    if configured != hooks:
        gaps.append("write_admission_not_armed:core.hooksPath")
    if not python:
        gaps.append("write_admission_not_armed:runtime_python")
    for name in HOOK_NAMES:
        launcher = hooks / name
        if not launcher.is_file() or not os.access(launcher, os.X_OK):
            gaps.append(f"write_admission_not_armed:{name}_launcher_missing")
        elif python and launcher.read_text(encoding="utf-8") != hook_launcher(python, name):
            gaps.append(f"write_admission_not_armed:{name}_launcher_drift")
    return {
        "hooks_path": hooks.as_posix(),
        "runtime_metadata_path": metadata.as_posix(),
        "python": python,
        "scripts": list(HOOK_NAMES),
        "required_gaps": gaps,
    }


def _git_path(root: Path, name: str) -> Path:
    completed = _git(root, "rev-parse", "--path-format=absolute", "--git-path", name)
    return Path(completed.stdout.strip())


def _configured_hooks_path(root: Path) -> Path | None:
    completed = _git(root, "config", "--path", "--get", "core.hooksPath", check=False)
    if completed.returncode or not completed.stdout.strip():
        return None
    configured = Path(completed.stdout.strip())
    return configured if configured.is_absolute() else (root / configured).resolve()


def _runtime_python(metadata: Path) -> str:
    if not metadata.is_file():
        return ""
    value = metadata.read_text(encoding="utf-8").strip()
    return value if value and Path(value).is_file() else ""


def _git(root: Path, *args: str, check: bool = True) -> subprocess.CompletedProcess[str]:
    environment = {key: value for key, value in os.environ.items() if not key.startswith("GIT_")}
    environment.update(
        {
            "GIT_NO_REPLACE_OBJECTS": "1",
            "GIT_OPTIONAL_LOCKS": "0",
            "GIT_CONFIG_NOSYSTEM": "1",
            "GIT_CONFIG_GLOBAL": os.devnull,
            "GIT_ATTR_NOSYSTEM": "1",
        }
    )
    return subprocess.run(
        (_GIT, *args),
        cwd=root,
        capture_output=True,
        check=check,
        text=True,
        env=environment,
    )
