from __future__ import annotations

from ethos_core.quality.models import QualityGateDescriptor

QUALITY_GATES = (
    QualityGateDescriptor(
        id="python-lint",
        kind="lint",
        command=("ruff", "check", "."),
        asset_classes=("python-code",),
        dimensions=("lint", "format"),
        execution_mode="adapter",
        evidence_class="diagnostic",
        trust_bearing=False,
        tool_adapter="ruff",
        writes_files=False,
        network_policy="offline",
        version_source="locked-toolchain",
    ),
    QualityGateDescriptor(
        id="python-tests",
        kind="test",
        command=("pytest", "tests", "-q"),
        asset_classes=("python-code",),
        dimensions=("test",),
        execution_mode="adapter",
        evidence_class="proof",
        trust_bearing=True,
        tool_adapter="pytest",
        writes_files=False,
        network_policy="offline",
        version_source="locked-toolchain",
        depends_on=("python-lint",),
    ),
    QualityGateDescriptor(
        id="markdown-links",
        kind="docs",
        command=("ethos", "quality", "markdown-links", "--json"),
        asset_classes=("markdown-docs",),
        dimensions=("links", "anchors"),
        execution_mode="inprocess",
        evidence_class="diagnostic",
        trust_bearing=True,
        tool_adapter="lychee",
        writes_files=False,
        network_policy="offline",
        version_source="adopter-toolchain",
    ),
    QualityGateDescriptor(
        id="markdown-structure",
        kind="docs",
        command=("ethos", "quality", "docs", "--json"),
        asset_classes=("markdown-docs",),
        dimensions=("front-matter", "command-examples", "anchors"),
        execution_mode="inprocess",
        evidence_class="contract",
        trust_bearing=True,
        tool_adapter="ethos-docs-profile",
        writes_files=False,
        network_policy="offline",
        version_source="product",
    ),
    QualityGateDescriptor(
        id="shell-lint",
        kind="lint",
        command=("ethos", "quality", "shell", "--json"),
        asset_classes=("shell-scripts",),
        dimensions=("lint",),
        execution_mode="inprocess",
        evidence_class="diagnostic",
        trust_bearing=True,
        tool_adapter="shellcheck",
        writes_files=False,
        network_policy="offline",
        version_source="adopter-toolchain",
    ),
    QualityGateDescriptor(
        id="toml-config",
        kind="config",
        command=("ethos", "quality", "toml", "--json"),
        asset_classes=("toml-config",),
        dimensions=("format", "schema"),
        execution_mode="inprocess",
        evidence_class="diagnostic",
        trust_bearing=True,
        tool_adapter="taplo",
        writes_files=False,
        network_policy="offline",
        version_source="adopter-toolchain",
    ),
    QualityGateDescriptor(
        id="json-contracts",
        kind="schema",
        command=("ethos", "quality", "schemas", "--json"),
        asset_classes=("json-contracts",),
        dimensions=("schema", "stable-ordering"),
        execution_mode="inprocess",
        evidence_class="contract",
        trust_bearing=True,
        tool_adapter="jsonschema",
        writes_files=False,
        network_policy="offline",
        version_source="product",
    ),
    QualityGateDescriptor(
        id="yaml-config",
        kind="config",
        command=("ethos", "quality", "yaml", "--json"),
        asset_classes=("yaml-config",),
        dimensions=("format", "projection-boundary"),
        execution_mode="inprocess",
        evidence_class="diagnostic",
        trust_bearing=True,
        tool_adapter="yamllint",
        writes_files=False,
        network_policy="offline",
        version_source="adopter-toolchain",
    ),
    QualityGateDescriptor(
        id="format-policy",
        kind="determinism",
        command=("ethos", "quality", "format-policy", "--json"),
        asset_classes=("toml-config", "json-contracts", "yaml-config"),
        dimensions=("format", "determinism"),
        execution_mode="inprocess",
        evidence_class="contract",
        trust_bearing=True,
        tool_adapter="ethos-format-policy",
        writes_files=False,
        network_policy="offline",
        version_source="product",
    ),
    QualityGateDescriptor(
        id="asset-determinism",
        kind="determinism",
        command=("ethos", "quality", "asset-policy", "--json"),
        asset_classes=("evidence", "release-artifacts", "adopter-profile"),
        dimensions=("determinism", "freshness", "provenance"),
        execution_mode="inprocess",
        evidence_class="contract",
        trust_bearing=True,
        tool_adapter="ethos-quality",
        writes_files=False,
        network_policy="offline",
        version_source="product",
    ),
    QualityGateDescriptor(
        id="schema-contracts",
        kind="schema",
        command=("ethos", "quality", "schemas", "--json"),
        asset_classes=("json-contracts",),
        dimensions=("schema",),
        execution_mode="inprocess",
        evidence_class="contract",
        trust_bearing=True,
        tool_adapter="jsonschema",
        writes_files=False,
        network_policy="offline",
        version_source="product",
    ),
    QualityGateDescriptor(
        id="proof-policy",
        kind="proof",
        command=("ethos", "quality", "proof-policy", "--json"),
        asset_classes=("evidence",),
        dimensions=("provenance", "freshness", "head-binding"),
        execution_mode="inprocess",
        evidence_class="proof",
        trust_bearing=True,
        tool_adapter="ethos-proof-policy",
        writes_files=False,
        network_policy="offline",
        version_source="product",
    ),
    QualityGateDescriptor(
        id="python-size",
        kind="determinism",
        command=("ethos", "quality", "code-size", "--json"),
        asset_classes=("python-code",),
        dimensions=("complexity", "determinism"),
        execution_mode="inprocess",
        evidence_class="contract",
        trust_bearing=True,
        tool_adapter="ethos-code-size",
        writes_files=False,
        network_policy="offline",
        version_source="product",
    ),
    QualityGateDescriptor(
        id="npm-pack",
        kind="package",
        command=("ethos", "quality", "npm", "--json"),
        asset_classes=("release-artifacts",),
        dimensions=("reproducibility", "attestation"),
        execution_mode="inprocess",
        evidence_class="proof",
        trust_bearing=True,
        tool_adapter="npm-pack",
        writes_files=False,
        network_policy="offline",
        version_source="locked-toolchain",
    ),
    QualityGateDescriptor(
        id="python-types",
        kind="typing",
        command=("ethos", "quality", "types", "--json"),
        asset_classes=("python-code",),
        dimensions=("typing", "determinism", "ratchet"),
        execution_mode="inprocess",
        evidence_class="contract",
        trust_bearing=True,
        tool_adapter="ty",
        writes_files=False,
        network_policy="offline",
        version_source="locked-toolchain",
        profile="product-toolchain",
        toolchain="uv-python",
    ),
    QualityGateDescriptor(
        id="import-boundaries",
        kind="architecture",
        command=("lint-imports", "--config", ".config/checks/import-linter/contracts.ini"),
        asset_classes=("python-code",),
        dimensions=("architecture", "acyclicity"),
        execution_mode="adapter",
        evidence_class="contract",
        trust_bearing=True,
        tool_adapter="import-linter",
        writes_files=False,
        network_policy="offline",
        version_source="locked-toolchain",
    ),
    QualityGateDescriptor(
        id="python-security",
        kind="security",
        command=("bandit", "-r", "packages", "-c", ".config/checks/bandit/bandit.yaml", "-q"),
        asset_classes=("python-code",),
        dimensions=("security", "supply-chain"),
        execution_mode="adapter",
        evidence_class="proof",
        trust_bearing=True,
        tool_adapter="bandit",
        writes_files=False,
        network_policy="offline",
        version_source="locked-toolchain",
    ),
)


def product_gate_plan() -> dict[str, object]:
    return {
        "schema_version": 1,
        "gates": [gate.to_dict() for gate in QUALITY_GATES],
    }


def quality_gate_registry() -> dict[str, QualityGateDescriptor]:
    return {gate.id: gate for gate in QUALITY_GATES}
