"""Read the exact repository-family Git hook runtime binding."""

from __future__ import annotations

import hashlib
import json
import os
import re
from pathlib import Path
from typing import NotRequired
from typing import TypedDict

from ethos.adapters.repo.git import git_common_dir
from ethos.adapters.repo.git import run_git
from ethos.adapters.repo.hook.source_identity import RuntimeSourceIdentity
from ethos.adapters.repo.hook.source_identity import expected_runtime_source
from ethos.adapters.repo.hook.source_identity import hook_runtime_repair_action

HOOK_NAMES = ("pre-commit", "pre-push", "reference-transaction")
_RUNTIME_LOCATOR = (
    r"\.\./\.\./runtime/(?P<digest>[a-f0-9]{64})/venv/(?P<python>bin/python|Scripts/python\.exe)"
)
_RUNTIME_RELATIVE = re.compile(f"^{_RUNTIME_LOCATOR}$")
_RUNTIME_IN_LAUNCHER = re.compile(_RUNTIME_LOCATOR)


class HookRuntimeBinding(TypedDict):
    """One repository family's exact generated-hook runtime provenance."""

    hooks_path: str
    runtime_manifest_path: str
    runtime_digest: str
    wheel_sha256: str
    source_commit: str
    source_tree: str
    expected_source_commit: str
    expected_source_tree: str
    current: bool
    next_action: str
    python: str
    scripts: list[str]
    required_gaps: list[str]
    generation_cleanup: NotRequired[dict[str, list[str]]]
    legacy_runtime_locator: NotRequired[dict[str, object]]
    linked_worktrees: NotRequired[list[dict[str, str]]]


def hook_launcher(runtime: str, name: str) -> str:
    """Render a Git-shell projection over one validated relative runtime."""
    if name not in HOOK_NAMES:
        message = f"hook_name_invalid:{name}"
        raise ValueError(message)
    if _RUNTIME_RELATIVE.fullmatch(runtime) is None:
        message = "hook_runtime_locator_invalid"
        raise ValueError(message)
    return (
        "#!/bin/sh\n"
        "# Generated by ethos hook install; Python owns all hook semantics.\n"
        'HOOK_DIR=${0%/*}; [ "$HOOK_DIR" = "$0" ] && HOOK_DIR=.\n'
        'HOOK_DIR=$(CDPATH= cd "$HOOK_DIR" && pwd)\n'
        f'exec "$HOOK_DIR/{runtime}" -I -m ethos.cli hook run {name} "$@"\n'
    )


def runtime_locator(venv: Path) -> str:
    """Return the validated relative Python locator for one runtime venv."""
    digest = venv.parent.name
    executable = "Scripts/python.exe" if os.name == "nt" else "bin/python"
    return f"../../runtime/{digest}/venv/{executable}"


def launcher_runtime_generation(hooks: Path, runtime_root: Path) -> Path:
    """Return the exact generated runtime referenced by one launcher generation."""
    launcher = hooks / "pre-commit"
    try:
        content = launcher.read_text(encoding="utf-8")
    except (OSError, UnicodeError) as error:
        message = "hook_runtime_consumers_unknown"
        raise ValueError(message) from error
    match = _RUNTIME_IN_LAUNCHER.search(content)
    if match is None:
        message = "hook_runtime_consumers_unknown"
        raise ValueError(message)
    runtime = runtime_root / match["digest"]
    if runtime.is_symlink() or not runtime.is_dir():
        message = "hook_runtime_consumers_unknown"
        raise ValueError(message)
    return runtime


def hook_generation_digest(launchers: dict[str, str]) -> str:
    """Return the canonical identity of one complete declared launcher set."""
    if tuple(launchers) != HOOK_NAMES:
        message = "hook_launcher_projection_invalid"
        raise ValueError(message)
    return hashlib.sha256(
        b"".join(
            name.encode() + b"\0" + content.encode() + b"\0" for name, content in launchers.items()
        )
    ).hexdigest()


def hook_runtime_binding(
    root: Path,
    *,
    expected_source: RuntimeSourceIdentity | None = None,
) -> HookRuntimeBinding:
    """Observe the configured common-dir runtime and its generated launchers."""
    repo = root.resolve()
    common = Path(git_common_dir(repo))
    generations = common / "ethos" / "hooks"
    configured = _configured_hooks_path(repo)
    hooks = configured or generations
    valid_generation = (
        configured is not None
        and configured.parent == generations
        and not generations.parent.is_symlink()
        and not generations.is_symlink()
        and not configured.is_symlink()
        and len(configured.name) == 64
        and not (set(configured.name) - set("0123456789abcdef"))
    )
    runtime, manifest, digest, wheel, source = (
        _runtime_from_launcher(hooks / "pre-commit", common / "ethos" / "runtime")
        if valid_generation
        else (None, None, "", "", None)
    )
    expected_source_identity, source_root = _expected_source(repo, expected_source)
    gaps: list[str] = []
    if not valid_generation:
        gaps.append("write_admission_not_armed:core.hooksPath")
    if runtime is None or manifest is None:
        gaps.append("write_admission_not_armed:runtime_manifest")
    if runtime is None:
        gaps.append("write_admission_not_armed:runtime_python")
    if expected_source_identity is None:
        gaps.append("write_admission_not_armed:runtime_expected_source_unavailable")
    elif source is not None and source != expected_source_identity:
        gaps.append("write_admission_not_armed:runtime_source_stale")
    gaps.extend(gap for name in HOOK_NAMES if (gap := _launcher_gap(hooks / name, name, runtime)))
    if runtime is not None:
        expected_launchers = {
            name: hook_launcher(runtime_locator(runtime.parent.parent), name) for name in HOOK_NAMES
        }
        if hooks.name != hook_generation_digest(expected_launchers):
            gaps.append("write_admission_not_armed:hook_generation_digest")
    return {
        "hooks_path": hooks.as_posix(),
        "runtime_manifest_path": manifest.as_posix() if manifest else "",
        "runtime_digest": digest,
        "wheel_sha256": wheel,
        "source_commit": source.commit if source else "",
        "source_tree": source.tree if source else "",
        "expected_source_commit": (
            expected_source_identity.commit if expected_source_identity else ""
        ),
        "expected_source_tree": expected_source_identity.tree if expected_source_identity else "",
        "current": not gaps,
        "next_action": hook_runtime_repair_action(repo, source_root) if gaps else "",
        "python": runtime.as_posix() if runtime else "",
        "scripts": list(HOOK_NAMES),
        "required_gaps": gaps,
    }


def _launcher_gap(launcher: Path, name: str, runtime: Path | None) -> str:
    if launcher.is_symlink() or not launcher.is_file() or not os.access(launcher, os.X_OK):
        return f"write_admission_not_armed:{name}_launcher_missing"
    if runtime is None:
        return ""
    try:
        current = launcher.read_text(encoding="utf-8")
    except (OSError, UnicodeError):
        current = ""
    expected = hook_launcher(runtime_locator(runtime.parent.parent), name)
    return "" if current == expected else f"write_admission_not_armed:{name}_launcher_drift"


def _runtime_from_launcher(
    launcher: Path, runtime_root: Path
) -> tuple[Path | None, Path | None, str, str, RuntimeSourceIdentity | None]:
    if not launcher.is_file():
        return None, None, "", "", None
    try:
        content = launcher.read_text(encoding="utf-8")
    except (OSError, UnicodeError):
        return None, None, "", "", None
    match = _RUNTIME_IN_LAUNCHER.search(content)
    if match is None:
        return None, None, "", "", None
    digest = match["digest"]
    runtime = runtime_root / digest / "venv" / match["python"]
    manifest = runtime.parents[2] / "manifest.json"
    try:
        payload = json.loads(manifest.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None, manifest, "", "", None
    wheel = str(payload.get("wheel_sha256") or "")
    files = payload.get("runtime_files")
    source = _manifest_source(payload)
    relative_runtime = runtime.relative_to(manifest.parent).as_posix()
    valid = (
        payload.get("schema_version") == 2
        and payload.get("runtime_digest") == digest
        and len(wheel) == 64
        and not (set(wheel) - set("0123456789abcdef"))
        and isinstance(payload.get("python_abi"), str)
        and bool(payload["python_abi"])
        and isinstance(payload.get("platform"), str)
        and bool(payload["platform"])
        and isinstance(files, dict)
        and source is not None
        and runtime.is_file()
        and files.get(relative_runtime) == _sha256(runtime)
    )
    return (runtime, manifest, digest, wheel, source) if valid else (None, manifest, "", "", None)


def _manifest_source(payload: dict[str, object]) -> RuntimeSourceIdentity | None:
    commit = str(payload.get("source_commit") or "")
    tree = str(payload.get("source_tree") or "")
    valid = all(
        len(value) in {40, 64} and not set(value) - set("0123456789abcdef")
        for value in (commit, tree)
    )
    return RuntimeSourceIdentity(commit=commit, tree=tree) if valid else None


def _expected_source(
    repo: Path,
    selected: RuntimeSourceIdentity | None,
) -> tuple[RuntimeSourceIdentity | None, Path | None]:
    if selected is not None:
        return selected, None
    try:
        return expected_runtime_source(repo)
    except (OSError, RuntimeError, ValueError):
        return None, None


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _configured_hooks_path(root: Path) -> Path | None:
    completed = run_git(root, "config", "--path", "--get", "core.hooksPath", check=False)
    if completed.returncode or not completed.stdout.strip():
        return None
    configured = Path(completed.stdout.strip())
    return configured.absolute() if configured.is_absolute() else (root / configured).absolute()
