"""Pure native hook launcher contract owned by the selected package."""

from __future__ import annotations

import hashlib
from pathlib import Path
from typing import TypedDict

from ethos.adapters.repo.runtime.filesystem import runtime_python

HOOK_NAMES = ("commit-msg", "pre-commit", "pre-push", "reference-transaction")


class HookContract(TypedDict):
    """Exact launcher contract reported by one immutable runtime package."""

    scripts: tuple[str, ...]
    launchers: dict[str, str]
    generation_digest: str


def hook_launcher(name: str) -> str:
    """Render a Git-shell projection over the canonical runtime selector."""
    if name not in HOOK_NAMES:
        message = f"hook_name_invalid:{name}"
        raise ValueError(message)
    executable = runtime_python(Path("python")).as_posix()
    return (
        "#!/bin/sh\n"
        "# Generated by ethos hook install; Python owns all hook semantics.\n"
        'HOOK_DIR=${0%/*}; [ "$HOOK_DIR" = "$0" ] && HOOK_DIR=.\n'
        'HOOK_DIR=$(CDPATH= cd "$HOOK_DIR" && pwd)\n'
        'RUNTIME_ROOT="$HOOK_DIR/../../runtime"\n'
        'CURRENT="$RUNTIME_ROOT/CURRENT"\n'
        'if [ -L "$CURRENT" ] || [ ! -f "$CURRENT" ]; then exit 1; fi\n'
        'exec 3<"$CURRENT" || exit 1\n'
        "IFS= read -r RUNTIME_DIGEST <&3 || exit 1\n"
        "RUNTIME_SELECTOR_EXTRA=\n"
        "IFS= read -r RUNTIME_SELECTOR_EXTRA <&3 && exit 1\n"
        '[ -z "$RUNTIME_SELECTOR_EXTRA" ] || exit 1\n'
        "exec 3<&-\n"
        'case "$RUNTIME_DIGEST" in *[!0-9a-f]*|"") exit 1;; esac\n'
        '[ "${#RUNTIME_DIGEST}" -eq 64 ] || exit 1\n'
        'RUNTIME="$RUNTIME_ROOT/$RUNTIME_DIGEST"\n'
        'if [ -L "$RUNTIME" ] || [ ! -d "$RUNTIME" ]; then exit 1; fi\n'
        f'exec "$RUNTIME/{executable}" -B -I -m ethos.cli hook run {name} "$@"\n'
    )


def hook_generation_digest(
    launchers: dict[str, str], *, scripts: tuple[str, ...] = HOOK_NAMES
) -> str:
    """Return the identity of one package-declared complete launcher contract."""
    if tuple(launchers) != scripts:
        message = "hook_launcher_projection_invalid"
        raise ValueError(message)
    return hashlib.sha256(
        b"".join(name.encode() + b"\0" + launchers[name].encode() + b"\0" for name in scripts)
    ).hexdigest()
