"""Read the exact repository-family Git hook runtime binding."""

from __future__ import annotations

import hashlib
import json
import os
import re
from pathlib import Path
from typing import TypedDict

from ethos.adapters.repo.git import git_common_dir
from ethos.adapters.repo.git import run_git

HOOK_NAMES = ("pre-commit", "commit-msg", "pre-push", "reference-transaction")
_RUNTIME_LOCATOR = (
    r"\.\./ethos/runtime/(?P<digest>[a-f0-9]{64})/venv/(?P<python>bin/python|Scripts/python\.exe)"
)
_RUNTIME_RELATIVE = re.compile(f"^{_RUNTIME_LOCATOR}$")
_RUNTIME_IN_LAUNCHER = re.compile(_RUNTIME_LOCATOR)


class HookRuntimeBinding(TypedDict):
    """One repository family's exact generated-hook runtime provenance."""

    hooks_path: str
    runtime_manifest_path: str
    runtime_digest: str
    wheel_sha256: str
    python: str
    scripts: list[str]
    required_gaps: list[str]


def hook_launcher(runtime: str, name: str) -> str:
    """Render a Git-shell projection over one validated relative runtime."""
    if name not in HOOK_NAMES:
        message = f"hook_name_invalid:{name}"
        raise ValueError(message)
    if _RUNTIME_RELATIVE.fullmatch(runtime) is None:
        message = "hook_runtime_locator_invalid"
        raise ValueError(message)
    return (
        "#!/bin/sh\n"
        "# Generated by ethos hook install; Python owns all hook semantics.\n"
        'HOOK_DIR=${0%/*}; [ "$HOOK_DIR" = "$0" ] && HOOK_DIR=.\n'
        'HOOK_DIR=$(CDPATH= cd "$HOOK_DIR" && pwd)\n'
        f'exec "$HOOK_DIR/{runtime}" -I -m ethos.cli hook run {name} "$@"\n'
    )


def hook_runtime_binding(root: Path) -> HookRuntimeBinding:
    """Observe the configured common-dir runtime and its generated launchers."""
    repo = root.resolve()
    common = Path(git_common_dir(repo))
    hooks = common / "ethos-hooks"
    configured = _configured_hooks_path(repo)
    runtime, manifest, digest, wheel = _runtime_from_launcher(hooks / "pre-commit")
    gaps: list[str] = []
    if configured != hooks:
        gaps.append("write_admission_not_armed:core.hooksPath")
    if runtime is None or manifest is None:
        gaps.append("write_admission_not_armed:runtime_manifest")
    if runtime is None:
        gaps.append("write_admission_not_armed:runtime_python")
    locator = _runtime_locator(digest, runtime) if runtime is not None else ""
    for name in HOOK_NAMES:
        launcher = hooks / name
        if not launcher.is_file() or not os.access(launcher, os.X_OK):
            gaps.append(f"write_admission_not_armed:{name}_launcher_missing")
        elif runtime is not None:
            text = launcher.read_text(encoding="utf-8")
            match = _RUNTIME_IN_LAUNCHER.search(text)
            if match is not None and match["digest"] != digest:
                gaps.append(f"write_admission_not_armed:{name}_launcher_runtime_split")
            elif text != hook_launcher(locator, name):
                gaps.append(f"write_admission_not_armed:{name}_launcher_drift")
    return {
        "hooks_path": hooks.as_posix(),
        "runtime_manifest_path": manifest.as_posix() if manifest else "",
        "runtime_digest": digest,
        "wheel_sha256": wheel,
        "python": runtime.as_posix() if runtime else "",
        "scripts": list(HOOK_NAMES),
        "required_gaps": gaps,
    }


def _runtime_from_launcher(launcher: Path) -> tuple[Path | None, Path | None, str, str]:
    if not launcher.is_file():
        return None, None, "", ""
    match = _RUNTIME_IN_LAUNCHER.search(launcher.read_text(encoding="utf-8"))
    if match is None:
        return None, None, "", ""
    digest = match["digest"]
    runtime = launcher.parent.parent / "ethos" / "runtime" / digest / "venv" / match["python"]
    manifest = runtime.parents[2] / "manifest.json"
    try:
        payload = json.loads(manifest.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None, manifest, "", ""
    wheel = str(payload.get("wheel_sha256") or "")
    files = payload.get("runtime_files")
    launchers = payload.get("hook_launchers")
    relative_runtime = runtime.relative_to(manifest.parent).as_posix()
    entrypoint = runtime.with_name("ethos.exe" if os.name == "nt" else "ethos")
    relative_entrypoint = entrypoint.relative_to(manifest.parent).as_posix()
    locator = _runtime_locator(digest, runtime)
    valid = (
        payload.get("schema_version") == 1
        and payload.get("runtime_digest") == digest
        and len(wheel) == 64
        and not (set(wheel) - set("0123456789abcdef"))
        and isinstance(payload.get("python_abi"), str)
        and bool(payload["python_abi"])
        and isinstance(payload.get("platform"), str)
        and bool(payload["platform"])
        and isinstance(files, dict)
        and runtime.is_file()
        and entrypoint.is_file()
        and set(files) == {relative_runtime, relative_entrypoint}
        and files.get(relative_runtime) == _sha256(runtime)
        and files.get(relative_entrypoint) == _sha256(entrypoint)
        and launchers
        == {
            name: hashlib.sha256(hook_launcher(locator, name).encode()).hexdigest()
            for name in HOOK_NAMES
        }
        and _entrypoint_bound_to_runtime(entrypoint, runtime)
    )
    return (runtime, manifest, digest, wheel) if valid else (None, manifest, "", "")


def _runtime_locator(digest: str, runtime: Path) -> str:
    executable = "Scripts/python.exe" if runtime.parent.name == "Scripts" else "bin/python"
    return f"../ethos/runtime/{digest}/venv/{executable}"


def _entrypoint_bound_to_runtime(entrypoint: Path, runtime: Path) -> bool:
    if os.name == "nt":
        return entrypoint.is_file()
    try:
        return entrypoint.read_text(encoding="utf-8").splitlines()[0] == f"#!{runtime}"
    except (OSError, UnicodeError, IndexError):
        return False


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _configured_hooks_path(root: Path) -> Path | None:
    completed = run_git(root, "config", "--path", "--get", "core.hooksPath", check=False)
    if completed.returncode or not completed.stdout.strip():
        return None
    configured = Path(completed.stdout.strip())
    return configured if configured.is_absolute() else (root / configured).resolve()
