"""Exercise starter evolution planning, provenance, and public admission."""

from __future__ import annotations

import subprocess
from types import SimpleNamespace
from typing import TYPE_CHECKING

import pytest

import ethos.adapters.mutation.lane_lifecycle.candidate_projection as candidate_projection
import ethos.adapters.repo.starter.evolution as evolution
from ethos.adapters.mutation.lane_lifecycle.start import default_worktree_path
from ethos.adapters.repo.attestation_set import read_attestation_set
from ethos.adapters.repo.starter.evolution import plan_starter_evolution
from ethos.contracts.branch.roles import load_branch_role_policy
from ethos.domain.adoption import adopt_repository
from tests.support.ethos_cli_runner import run_ethos
from tests.support.ethos_cli_runner import run_ethos_blocked
from tests.support.governed_repository import commit_fixture_file
from tests.support.governed_repository import create_change_source_lane
from tests.support.governed_repository import git
from tests.support.governed_repository import init_git_repo
from tests.support.runtime_scenarios import install_fixture_hook_runtime

if TYPE_CHECKING:
    from pathlib import Path


def _formed_python_repo(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    target = tmp_path / "new-project"
    request = {
        "create": True,
        "purpose": "Old purpose.",
        "starter": "python-library",
        "author_name": "Test Contributor",
        "author_email": "test@example.invalid",
    }
    preview = adopt_repository(target, **request)
    assert preview.verdict == "pass"
    monkeypatch.setattr(
        candidate_projection, "install_hook_launchers", install_fixture_hook_runtime
    )
    applied = adopt_repository(
        target,
        **request,
        apply=True,
        authorize=True,
        expect_plan_digest=str(preview.data["plan_digest"]),
    )
    assert applied.verdict == "pass"
    git(target, "config", "user.name", "Test Contributor")
    git(target, "config", "user.email", "test@example.invalid")
    return target


def test_formed_starter_evolution_preserves_authored_customization(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Recorded formation, not caller-selected paths, supplies old starter scope."""
    repo = _formed_python_repo(tmp_path, monkeypatch)
    custom = repo / "src" / "custom.py"
    custom.write_text("value = 1\n", encoding="utf-8")
    git(repo, "add", "src/custom.py")
    git(repo, "commit", "-m", "feat: customize project")
    current = git(repo, "rev-parse", "HEAD")
    refs = git(repo, "show-ref")

    report = plan_starter_evolution(repo, purpose="New purpose.")

    assert report["verdict"] == "pass"
    assert report["changed_paths"] == ["pyproject.toml"]
    assert "New purpose." in report["patch"]
    assert git(repo, "rev-parse", "HEAD") == current
    assert git(repo, "show-ref") == refs
    assert custom.read_text(encoding="utf-8") == "value = 1\n"


def test_formed_starter_evolution_reports_conflicting_authorship(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """A recorded generator source does not authorize replacing an authored edit."""
    repo = _formed_python_repo(tmp_path, monkeypatch)
    pyproject = repo / "pyproject.toml"
    pyproject.write_text(pyproject.read_text().replace("Old purpose.", "Authored purpose."))
    git(repo, "add", "pyproject.toml")
    git(repo, "commit", "-m", "feat: customize project purpose")
    before = pyproject.read_bytes()

    report = plan_starter_evolution(repo, purpose="New purpose.")

    assert report["verdict"] == "block"
    assert report["required_gaps"] == ["starter_evolution_conflict"]
    assert pyproject.read_bytes() == before
    decision = adopt_repository(repo, evolve_starter=True, purpose="New purpose.")
    assert decision.user_decision_required is True


def test_starter_evolution_requires_formation_provenance(tmp_path: Path) -> None:
    """A normal authored repository cannot declare any path generated by assertion."""
    repo = init_git_repo(tmp_path / "unformed")

    report = plan_starter_evolution(repo, purpose="New purpose.")

    assert report["verdict"] == "block"
    assert report["required_gaps"] == ["starter_evolution_provenance_missing"]


@pytest.mark.parametrize(
    ("corruption", "gap"),
    [
        ("duplicate", "starter_evolution_provenance_ambiguous"),
        ("claim", "starter_evolution_provenance_invalid"),
        ("generator", "starter_evolution_provenance_invalid"),
        ("missing-baseline", "starter_evolution_baseline_unavailable"),
        ("missing-project-name", "starter_evolution_provenance_invalid"),
        ("unsafe-project-name", "starter_evolution_provenance_invalid"),
    ],
)
def test_starter_evolution_rejects_untrusted_formation_provenance(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, corruption: str, gap: str
) -> None:
    """A recorded result must not authorize an unrelated starter or Git base."""
    repo = _formed_python_repo(tmp_path, monkeypatch)
    before = git(repo, "rev-parse", "HEAD")
    _set, records = read_attestation_set(repo)
    record = next(item for item in records if item.predicate == "effect:starter-formation")
    body = record.model_dump(mode="json")["payload"]["body"]
    if corruption == "claim":
        body["claim"]["operation"] = "other"
    elif corruption == "generator":
        body["input"]["sources"]["starter"] = "foundation"
    elif corruption == "missing-baseline":
        body["output"]["head"] = "0" * len(before)
    fake = SimpleNamespace(
        predicate=record.predicate,
        verdict=record.verdict,
        payload=SimpleNamespace(kind=record.payload.kind, body=body),
    )
    selected = (fake, fake) if corruption == "duplicate" else (fake,)
    monkeypatch.setattr(evolution, "read_attestation_set", lambda _root: ("", selected))
    if corruption in {"missing-project-name", "unsafe-project-name"}:
        source = (
            b"[project]\n"
            if corruption == "missing-project-name"
            else b'[project]\nname = "outside/path"\n'
        )
        original_run_git = evolution.run_git

        def project_object(root: Path, *args, **kwargs):
            if args and args[0] == "show":
                return subprocess.CompletedProcess(args, 0, stdout=source, stderr=b"")
            return original_run_git(root, *args, **kwargs)

        monkeypatch.setattr(evolution, "run_git", project_object)
    report = plan_starter_evolution(repo, purpose="A revised purpose.")
    assert report["required_gaps"] == [gap]
    assert report["patch"] == ""
    assert git(repo, "rev-parse", "HEAD") == before


@pytest.mark.parametrize(
    ("failure", "gap"),
    [
        ("purpose", "starter_evolution_purpose_missing"),
        ("repository", "starter_evolution_repository_unavailable"),
        ("generator", "formation_starter_generation_failed"),
        ("changed-output", "starter_evolution_generation_changed"),
        ("observation", "starter_evolution_observation_unknown"),
    ],
)
def test_starter_evolution_plan_preserves_distinct_failure_owners(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch, failure: str, gap: str
) -> None:
    """Review never upgrades unavailable source, generator or evidence to a patch."""
    repo = _formed_python_repo(tmp_path, monkeypatch)
    before = git(repo, "rev-parse", "HEAD")
    if failure == "repository":
        original_run_git = evolution.run_git

        def unavailable_head(root: Path, *args, **kwargs):
            if args and args[0] == "rev-parse":
                return subprocess.CompletedProcess(args, 1, stdout="", stderr="missing")
            return original_run_git(root, *args, **kwargs)

        monkeypatch.setattr(evolution, "run_git", unavailable_head)
    elif failure == "generator":
        monkeypatch.setattr(
            evolution,
            "compose_starter",
            lambda *_args: ({}, {}, "formation_starter_generation_failed", "native error"),
        )
    elif failure == "changed-output":

        def changed(candidate: Path, *_args):
            (candidate / "pyproject.toml").write_text("changed\n", encoding="utf-8")
            return {}, {"pyproject.toml": "0" * 64}, "", ""

        monkeypatch.setattr(evolution, "compose_starter", changed)
    elif failure == "observation":

        def unavailable(_root: Path):
            message = "attestation unavailable"
            raise OSError(message)

        monkeypatch.setattr(evolution, "read_attestation_set", unavailable)
    report = plan_starter_evolution(repo, purpose="  " if failure == "purpose" else "New purpose.")
    assert report["required_gaps"] == [gap]
    assert report["patch"] == ""
    assert git(repo, "rev-parse", "HEAD") == before


def test_starter_evolution_uses_original_name_from_sibling_worktree(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """A Work Lane directory name cannot silently rename native generator output."""
    repo = _formed_python_repo(tmp_path, monkeypatch)
    candidate = default_worktree_path(repo, load_branch_role_policy(repo).candidate_branch)
    assert candidate.is_dir()

    report = plan_starter_evolution(candidate, purpose="New purpose.")

    assert report["verdict"] == "pass"
    assert report["changed_paths"] == ["pyproject.toml"]
    assert "src/new_project/__init__.py" in report["source_inputs"]["new_files_sha256"]


def test_starter_evolution_blocks_dirty_worktree_before_generation(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """A preview cannot imply that uncommitted authored bytes were merged."""
    repo = _formed_python_repo(tmp_path, monkeypatch)
    (repo / "notes.txt").write_text("authored and uncommitted\n", encoding="utf-8")

    report = plan_starter_evolution(repo, purpose="New purpose.")

    assert report["verdict"] == "block"
    assert report["required_gaps"] == ["starter_evolution_worktree_dirty"]
    assert (repo / "notes.txt").read_text(encoding="utf-8") == "authored and uncommitted\n"


def test_starter_evolution_public_preview_is_read_only(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Installed callers reach the same reviewable candidate without direct effects."""
    repo = _formed_python_repo(tmp_path, monkeypatch)
    before = git(repo, "rev-parse", "HEAD")
    refs = git(repo, "show-ref")

    result = run_ethos(
        "adopt",
        "--evolve-starter",
        "--purpose",
        "New purpose.",
        "--root",
        str(repo),
        "--json",
        cwd=repo,
    )

    assert result["verdict"] == "pass"
    assert result["data"]["changed_paths"] == ["pyproject.toml"]
    assert "New purpose." in result["data"]["patch"]
    assert git(repo, "rev-parse", "HEAD") == before
    assert git(repo, "show-ref") == refs


def test_starter_evolution_public_apply_refuses_generator_authority(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """A starter preview cannot become a repository write by adding --apply."""
    repo = _formed_python_repo(tmp_path, monkeypatch)
    before = (repo / "pyproject.toml").read_bytes()

    result = run_ethos_blocked(
        "adopt",
        "--evolve-starter",
        "--purpose",
        "New purpose.",
        "--root",
        str(repo),
        "--apply",
        "--authorize",
        "--json",
        cwd=repo,
    )

    assert result["required_gaps"] == ["starter_evolution_requires_work_lane"]
    assert (repo / "pyproject.toml").read_bytes() == before


def test_starter_evolution_reviewed_patch_uses_existing_lane_admission(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """An authored lane admits the exact reviewed patch, not a generator-owned write."""
    repo = _formed_python_repo(tmp_path, monkeypatch)
    actor = "agent:test:case:starter-upgrade"
    lane = create_change_source_lane(
        repo,
        tmp_path / "starter-upgrade-lane",
        branch="work/starter-upgrade",
        holder_ref=actor,
        base_ref=load_branch_role_policy(repo).candidate_branch,
    )
    assert not (lane / "openspec/specs").exists()
    commit_fixture_file(lane, "src/custom.py", "value = 1\n", "feat: authored extension")
    authored = (lane / "src/custom.py").read_bytes()
    monkeypatch.setenv("ETHOS_ACTOR", actor)
    monkeypatch.setenv("ETHOS_CHANGE", "fixture-change")

    preview = run_ethos(
        "adopt",
        "--evolve-starter",
        "--purpose",
        "New purpose.",
        "--root",
        str(lane),
        "--json",
        cwd=lane,
    )
    assert preview["verdict"] == "pass"
    assert preview["data"]["changed_paths"] == ["pyproject.toml"]
    patch = str(preview["data"]["patch"])
    patch_path = tmp_path / "reviewed.patch"
    patch_path.write_text(patch, encoding="utf-8")
    before = git(lane, "rev-parse", "HEAD")

    admitted = run_ethos(
        "lane",
        "prewrite",
        "--paths",
        "pyproject.toml",
        "--patch",
        str(patch_path),
        "--editor-root",
        str(lane),
        "--require-editor-root",
        "--root",
        str(lane),
        "--json",
        cwd=lane,
    )
    assert admitted["verdict"] == "pass"
    assert admitted["data"]["patch_admission"]["paths"] == ["pyproject.toml"]
    assert admitted["data"]["request_binding"]["expected_state"]["head"] == before
    subprocess.run(
        ["git", "apply", "--whitespace=error-all", "-"],
        input=patch,
        text=True,
        cwd=lane,
        check=True,
        capture_output=True,
    )
    assert (lane / "src/custom.py").read_bytes() == authored
    assert "New purpose." in (lane / "pyproject.toml").read_text(encoding="utf-8")
    git(lane, "add", "pyproject.toml")
    git(lane, "commit", "-m", "chore: upgrade reviewed starter")
    assert git(lane, "status", "--porcelain") == ""
    stale = run_ethos_blocked(
        "lane",
        "prewrite",
        "--paths",
        "pyproject.toml",
        "--patch",
        str(patch_path),
        "--editor-root",
        str(lane),
        "--require-editor-root",
        "--root",
        str(lane),
        "--json",
        cwd=lane,
    )
    assert stale["data"]["patch_admission"]["reason"] == "prewrite_patch_preimage_mismatch"
